[package]
name = "withdraw"
type = "bin"
authors = ["Astra Team"]
compiler_version = ">=1.0.0"

[dependencies]
common = { path = "../common" }
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }
